# Generated by Django 2.2.6 on 2019-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('trademark', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.CharField(max_length=10, verbose_name='Yıl')),
                ('gear', models.CharField(max_length=20, verbose_name='Vites')),
                ('fuel', models.CharField(max_length=20, verbose_name='Yakıt')),
                ('carClass', models.CharField(max_length=30, verbose_name='Sınıf')),
                ('horsePower', models.CharField(max_length=5, verbose_name='Beygir Gücü')),
                ('baggageVolume', models.CharField(max_length=15, verbose_name='Bagaj Hacmi')),
                ('price', models.IntegerField(verbose_name='Günlük Ücret')),
            ],
        ),
    ]
