# Generated by Django 2.2.6 on 2019-11-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalDate', models.DateField(verbose_name='Kiralanma Tarihi')),
                ('totalDays', models.IntegerField(verbose_name='Gün Sayısı')),
                ('transactionDate', models.DateTimeField(auto_now_add=True, verbose_name='Islem Tarihi')),
                ('rentedCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autos.Autos', verbose_name='Kiralanan Otomobil')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kiralayan Kullanıcı')),
            ],
        ),
    ]
