# Generated by Django 2.2.6 on 2020-03-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi'),
        ),
    ]
